<?php

namespace Database\Seeders\PeluangKarir;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Loker;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class LokerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Loker::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $lokers = [
            [
                'title' => 'Full Stack Developer (Laravel + React)',
                'company' => 'PT Teknologi Inovasi Indonesia (TechInova)',
                'location' => 'Jakarta Selatan',
                'type' => 'Full Time',
                'work_model' => 'Hybrid',
                'experience_level' => 'Mid-Level',
                'categories' => ['IT & Software', 'Web Development', 'Engineering'],
                'salary_min' => 12000000,
                'salary_max' => 18000000,
                'deadline' => Carbon::now()->addDays(14),
                'posted_date' => Carbon::now()->subDays(2),
                'logo' => 'loker-logos/inovasi-logo.png',
                'image' => null,
                'application_url' => 'https://linkedin.com/jobs',
                'is_active' => true,
                'description' => '<p>Kami mencari Full Stack Developer yang bersemangat untuk bergabung dengan tim engineering kami yang berkembang pesat. Anda akan bertanggung jawab untuk mengembangkan fitur baru dan memelihara platform e-commerce kami.</p><p>Sebagai bagian dari tim, Anda akan bekerja sama dengan Product Manager dan UI/UX Designer.</p>',
                'requirements' => '<ul><li>Pengalaman minimal 2-3 tahun menggunakan <strong>Laravel</strong> dan <strong>React.js</strong>.</li><li>Memahami RESTful API dan manajemen database (MySQL/PostgreSQL).</li><li>Terbiasa menggunakan Git dan Docker.</li><li>Memiliki kemampuan problem solving yang baik.</li><li>Dapat bekerja secara mandiri maupun dalam tim.</li></ul>',
                'benefits' => '<ul><li>BPJS Kesehatan & Ketenagakerjaan.</li><li>Allowance WFH/Internet.</li><li>Laptop kantor (MacBook/ThinkPad).</li><li>Bonus kinerja tahunan.</li><li>Program pengembangan karir dan training.</li></ul>',
            ],
            [
                'title' => 'Social Media Specialist',
                'company' => 'Creative Buzz Agency',
                'location' => 'Tangerang Selatan',
                'type' => 'Contract',
                'work_model' => 'Onsite',
                'experience_level' => 'Junior',
                'categories' => ['Marketing', 'Creative', 'Social Media'],
                'salary_min' => 5000000,
                'salary_max' => 7000000,
                'deadline' => Carbon::now()->addDays(7),
                'posted_date' => Carbon::now()->subDays(5),
                'logo' => 'loker-logos/buzz-logo.png',
                'image' => null,
                'application_url' => 'https://jobstreet.co.id',
                'is_active' => true,
                'description' => '<p>Creative Buzz Agency mencari Social Media Specialist yang kreatif dan up-to-date dengan tren terkini (TikTok/Reels). Anda akan mengelola akun klien kami dari industri F&B dan Fashion.</p>',
                'requirements' => '<ul><li>Pendidikan minimal D3/S1 Komunikasi, Pemasaran, atau jurusan terkait.</li><li>Fasih menggunakan tools editing mobile (CapCut, VN) dan Canva.</li><li>Memahami algoritma Instagram dan TikTok.</li><li>Mampu membuat Content Plan dan Copywriting yang menarik.</li><li>Portofolio konten wajib dilampirkan.</li></ul>',
                'benefits' => '<ul><li>Lingkungan kerja santai dan kreatif.</li><li>Free snack & coffee di kantor.</li><li>Team building bulanan.</li><li>Kesempatan menjadi karyawan tetap.</li></ul>',
            ],
            [
                'title' => 'Finance & Accounting Staff',
                'company' => 'PT Maju Makmur Sentosa',
                'location' => 'Jakarta Pusat',
                'type' => 'Full Time',
                'work_model' => 'Onsite',
                'experience_level' => 'Fresh Graduate',
                'categories' => ['Finance', 'Accounting', 'Admin'],
                'salary_min' => 5500000,
                'salary_max' => 6500000,
                'deadline' => Carbon::now()->addDays(30),
                'posted_date' => Carbon::now()->subDays(1),
                'logo' => 'loker-logos/makmur-sentosa-logo.jpeg',
                'image' => 'loker-images/images-loker-dummy.png',
                'application_url' => null,
                'is_active' => true,
                'description' => '<p>Dibutuhkan segera Staff Finance & Accounting untuk perusahaan distributor FMCG. Bertanggung jawab atas pencatatan transaksi harian, petty cash, dan pembuatan laporan keuangan bulanan.</p>',
                'requirements' => '<ul><li>S1 Akuntansi dengan IPK minimal 3.00.</li><li>Memahami dasar-dasar akuntansi dan perpajakan (PPh 21, 23, PPN).</li><li>Mahir menggunakan Microsoft Excel (VLOOKUP, Pivot Table).</li><li>Teliti, jujur, dan bertanggung jawab.</li><li>Bersedia ditempatkan di Jakarta Pusat.</li></ul>',
                'benefits' => '<ul><li>Gaji pokok + Uang makan.</li><li>Tunjangan transportasi.</li><li>THR dan Bonus Tahunan.</li><li>Jenjang karir yang jelas.</li></ul>',
            ],
            [
                'title' => 'UI/UX Designer',
                'company' => 'StartUp Unicorn Indo',
                'location' => 'Remote (Indonesia)',
                'type' => 'Full Time',
                'work_model' => 'Remote',
                'experience_level' => 'Senior',
                'categories' => ['Design', 'IT & Software', 'Product'],
                'salary_min' => 15000000,
                'salary_max' => 25000000,
                'deadline' => Carbon::now()->addDays(20),
                'posted_date' => Carbon::now()->subDays(10),
                'logo' => 'loker-logos/unicorn-logo.jpg',
                'image' => null,
                'application_url' => 'https://glints.com',
                'is_active' => true,
                'description' => '<p>Kami mencari Senior UI/UX Designer untuk memimpin desain produk aplikasi mobile kami yang digunakan oleh jutaan pengguna. Anda akan mentransformasi masalah pengguna menjadi solusi desain yang intuitif dan indah.</p>',
                'requirements' => '<ul><li>Pengalaman minimal 4 tahun di bidang Product Design.</li><li>Menguasai <strong>Figma</strong> (Auto layout, Components, Design System).</li><li>Memiliki pemahaman kuat tentang User Research dan Usability Testing.</li><li>Dapat berkolaborasi dengan Developer dan PM.</li><li>Portfolio yang kuat menampilkan studi kasus.</li></ul>',
                'benefits' => '<ul><li>Full Remote Work (Bekerja dari mana saja).</li><li>Asuransi kesehatan swasta.</li><li>Cuti tahunan 15 hari.</li><li>Budget setup WFH (Kursi/Meja/Monitor).</li><li>Stock Options (ESOP).</li></ul>',
            ],
            [
                'title' => 'HR Generalist (Recruitment & Admin)',
                'company' => 'PT Solusi Daya Manusia',
                'location' => 'Bekasi',
                'type' => 'Part Time',
                'work_model' => 'Onsite',
                'experience_level' => 'Mid-Level',
                'categories' => ['Human Resources', 'Admin'],
                'salary_min' => 4000000,
                'salary_max' => 5000000,
                'deadline' => Carbon::now()->addDays(5),
                'posted_date' => Carbon::now(),
                'logo' => null,
                'image' => null,
                'application_url' => null,
                'is_active' => true,
                'description' => '<p>Mencari HR Generalist paruh waktu untuk membantu proses rekrutmen karyawan lapangan dan administrasi BPJS.</p>',
                'requirements' => '<ul><li>Pengalaman minimal 1 tahun di bidang HR.</li><li>Memahami UU Ketenagakerjaan.</li><li>Terbiasa melakukan screening CV dan interview awal.</li><li>Domisili Bekasi diutamakan.</li></ul>',
                'benefits' => '<ul><li>Jadwal kerja fleksibel.</li><li>Transport allowance.</li></ul>',
            ],
            [
                'title' => 'Full Stack Developer (Laravel + React)',
                'company' => 'PT Teknologi Inovasi Indonesia (TechInova)',
                'location' => 'Jakarta Selatan',
                'type' => 'Full Time',
                'work_model' => 'Hybrid',
                'experience_level' => 'Mid-Level',
                'categories' => ['IT & Software', 'Web Development', 'Engineering'],
                'salary_min' => 12000000,
                'salary_max' => 18000000,
                'deadline' => Carbon::now()->addDays(14),
                'posted_date' => Carbon::now()->subDays(2),
                'logo' => null,
                'image' => null,
                'application_url' => 'https://linkedin.com/jobs',
                'is_active' => true,
                'description' => '<p>Kami mencari Full Stack Developer yang bersemangat untuk bergabung dengan tim engineering kami yang berkembang pesat. Anda akan bertanggung jawab untuk mengembangkan fitur baru dan memelihara platform e-commerce kami.</p><p>Sebagai bagian dari tim, Anda akan bekerja sama dengan Product Manager dan UI/UX Designer.</p>',
                'requirements' => '<ul><li>Pengalaman minimal 2-3 tahun menggunakan <strong>Laravel</strong> dan <strong>React.js</strong>.</li><li>Memahami RESTful API dan manajemen database (MySQL/PostgreSQL).</li><li>Terbiasa menggunakan Git dan Docker.</li><li>Memiliki kemampuan problem solving yang baik.</li><li>Dapat bekerja secara mandiri maupun dalam tim.</li></ul>',
                'benefits' => '<ul><li>BPJS Kesehatan & Ketenagakerjaan.</li><li>Allowance WFH/Internet.</li><li>Laptop kantor (MacBook/ThinkPad).</li><li>Bonus kinerja tahunan.</li><li>Program pengembangan karir dan training.</li></ul>',
            ],
            [
                'title' => 'Social Media Specialist',
                'company' => 'Creative Buzz Agency',
                'location' => 'Tangerang Selatan',
                'type' => 'Contract',
                'work_model' => 'Onsite',
                'experience_level' => 'Junior',
                'categories' => ['Marketing', 'Creative', 'Social Media'],
                'salary_min' => 5000000,
                'salary_max' => 7000000,
                'deadline' => Carbon::now()->addDays(7),
                'posted_date' => Carbon::now()->subDays(5),
                'logo' => null,
                'image' => null,
                'application_url' => 'https://jobstreet.co.id',
                'is_active' => true,
                'description' => '<p>Creative Buzz Agency mencari Social Media Specialist yang kreatif dan up-to-date dengan tren terkini (TikTok/Reels). Anda akan mengelola akun klien kami dari industri F&B dan Fashion.</p>',
                'requirements' => '<ul><li>Pendidikan minimal D3/S1 Komunikasi, Pemasaran, atau jurusan terkait.</li><li>Fasih menggunakan tools editing mobile (CapCut, VN) dan Canva.</li><li>Memahami algoritma Instagram dan TikTok.</li><li>Mampu membuat Content Plan dan Copywriting yang menarik.</li><li>Portofolio konten wajib dilampirkan.</li></ul>',
                'benefits' => '<ul><li>Lingkungan kerja santai dan kreatif.</li><li>Free snack & coffee di kantor.</li><li>Team building bulanan.</li><li>Kesempatan menjadi karyawan tetap.</li></ul>',
            ],
            [
                'title' => 'Finance & Accounting Staff',
                'company' => 'PT Maju Makmur Sentosa',
                'location' => 'Jakarta Pusat',
                'type' => 'Full Time',
                'work_model' => 'Onsite',
                'experience_level' => 'Fresh Graduate',
                'categories' => ['Finance', 'Accounting', 'Admin'],
                'salary_min' => 5500000,
                'salary_max' => 6500000,
                'deadline' => Carbon::now()->addDays(30),
                'posted_date' => Carbon::now()->subDays(1),
                'logo' => null,
                'image' => null,
                'application_url' => null,
                'is_active' => true,
                'description' => '<p>Dibutuhkan segera Staff Finance & Accounting untuk perusahaan distributor FMCG. Bertanggung jawab atas pencatatan transaksi harian, petty cash, dan pembuatan laporan keuangan bulanan.</p>',
                'requirements' => '<ul><li>S1 Akuntansi dengan IPK minimal 3.00.</li><li>Memahami dasar-dasar akuntansi dan perpajakan (PPh 21, 23, PPN).</li><li>Mahir menggunakan Microsoft Excel (VLOOKUP, Pivot Table).</li><li>Teliti, jujur, dan bertanggung jawab.</li><li>Bersedia ditempatkan di Jakarta Pusat.</li></ul>',
                'benefits' => '<ul><li>Gaji pokok + Uang makan.</li><li>Tunjangan transportasi.</li><li>THR dan Bonus Tahunan.</li><li>Jenjang karir yang jelas.</li></ul>',
            ],
            [
                'title' => 'UI/UX Designer',
                'company' => 'StartUp Unicorn Indo',
                'location' => 'Remote (Indonesia)',
                'type' => 'Full Time',
                'work_model' => 'Remote',
                'experience_level' => 'Senior',
                'categories' => ['Design', 'IT & Software', 'Product'],
                'salary_min' => 15000000,
                'salary_max' => 25000000,
                'deadline' => Carbon::now()->addDays(20),
                'posted_date' => Carbon::now()->subDays(10),
                'logo' => null,
                'image' => null,
                'application_url' => 'https://glints.com',
                'is_active' => true,
                'description' => '<p>Kami mencari Senior UI/UX Designer untuk memimpin desain produk aplikasi mobile kami yang digunakan oleh jutaan pengguna. Anda akan mentransformasi masalah pengguna menjadi solusi desain yang intuitif dan indah.</p>',
                'requirements' => '<ul><li>Pengalaman minimal 4 tahun di bidang Product Design.</li><li>Menguasai <strong>Figma</strong> (Auto layout, Components, Design System).</li><li>Memiliki pemahaman kuat tentang User Research dan Usability Testing.</li><li>Dapat berkolaborasi dengan Developer dan PM.</li><li>Portfolio yang kuat menampilkan studi kasus.</li></ul>',
                'benefits' => '<ul><li>Full Remote Work (Bekerja dari mana saja).</li><li>Asuransi kesehatan swasta.</li><li>Cuti tahunan 15 hari.</li><li>Budget setup WFH (Kursi/Meja/Monitor).</li><li>Stock Options (ESOP).</li></ul>',
            ],
            [
                'title' => 'HR Generalist (Recruitment & Admin)',
                'company' => 'PT Solusi Daya Manusia',
                'location' => 'Bekasi',
                'type' => 'Part Time',
                'work_model' => 'Onsite',
                'experience_level' => 'Mid-Level',
                'categories' => ['Human Resources', 'Admin'],
                'salary_min' => 4000000,
                'salary_max' => 5000000,
                'deadline' => Carbon::now()->addDays(5),
                'posted_date' => Carbon::now(),
                'logo' => null,
                'image' => null,
                'application_url' => null,
                'is_active' => true,
                'description' => '<p>Mencari HR Generalist paruh waktu untuk membantu proses rekrutmen karyawan lapangan dan administrasi BPJS.</p>',
                'requirements' => '<ul><li>Pengalaman minimal 1 tahun di bidang HR.</li><li>Memahami UU Ketenagakerjaan.</li><li>Terbiasa melakukan screening CV dan interview awal.</li><li>Domisili Bekasi diutamakan.</li></ul>',
                'benefits' => '<ul><li>Jadwal kerja fleksibel.</li><li>Transport allowance.</li></ul>',
            ],
        ];

        foreach ($lokers as $loker) {
            $loker['slug'] = Str::slug($loker['title']) . '-' . Str::random(5);
            
            Loker::create($loker);
        }
    }
}
