<?php

namespace Database\Seeders\PeluangKarir;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Sertifikasi;
use Illuminate\Support\Str;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Seeder;

class SertifikasiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        Sertifikasi::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
        $sertifikasis = [
            [
                'title' => 'Google Data Analytics Professional Certificate',
                'provider_name' => 'Coursera (Google)',
                'description' => 'Pelajari keterampilan in-demand agar siap kerja dalam waktu kurang dari 6 bulan. Tidak perlu gelar atau pengalaman.',
                'content' => '<p>Ini adalah jalur karir Anda menuju pekerjaan di bidang analitik data. Dalam program ini, Anda akan belajar keterampilan analitis, alat (SQL, R, Tableau), dan visualisasi data.</p>',
                'categories' => ['Data Science', 'Analytics'],
                'type' => 'Sertifikasi',
                'level' => 'Beginner',
                'mode' => 'Online',
                'location' => null,
                'duration' => '6 Bulan (10 jam/minggu)',
                'is_self_paced' => true,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'fee' => 200000,
                'is_free' => false,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>Tidak ada prasyarat khusus</li><li>Kemampuan dasar komputer</li></ul>',
                'benefits' => '<ul><li>Sertifikat Profesional dari Google</li><li>Portofolio Proyek</li><li>Akses ke Career Resources</li></ul>',
                'syllabus' => '<ol><li>Foundations: Data, Data, Everywhere</li><li>Ask Questions to Make Data-Driven Decisions</li><li>Prepare Data for Exploration</li></ol>',
                'registration_url' => 'https://www.coursera.org/professional-certificates/google-data-analytics',
                'registration_deadline' => Carbon::now()->addDays(30),
                'is_registration_open' => true,
                'quota' => null,
                'tags' => ['google', 'data-science', 'sql', 'python'],
                'logo' => 'sertifikasi/logos/coursera-logo.png',
            ],
            [
                'title' => 'AWS Certified Cloud Practitioner',
                'provider_name' => 'Amazon Web Services (AWS)',
                'description' => 'Validasi pemahaman menyeluruh tentang platform AWS Cloud, termasuk konsep dasar keamanan, arsitektur, dan penetapan harga.',
                'content' => '<p>Kredensial ini membantu organisasi mengidentifikasi dan mengembangkan bakat dengan pengetahuan kritis terkait inisiatif cloud. Sertifikasi ini memvalidasi kelancaran cloud dan pengetahuan dasar AWS.</p>',
                'categories' => ['Cloud Computing', 'IT Infrastructure'],
                'type' => 'Sertifikasi',
                'level' => 'Beginner',
                'mode' => 'Online',
                'location' => null,
                'duration' => '90 Menit (Ujian)',
                'is_self_paced' => true,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(12),
                'fee' => 1000000,
                'is_free' => false,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>Pengetahuan dasar layanan IT</li><li>Pemahaman dasar tentang AWS Cloud</li></ul>',
                'benefits' => '<ul><li>Kredensial industri yang diakui global</li><li>Lencana digital AWS</li></ul>',
                'syllabus' => '<ul><li>Cloud Concepts</li><li>Security and Compliance</li><li>Technology</li><li>Billing and Pricing</li></ul>',
                'registration_url' => 'https://aws.amazon.com/certification/certified-cloud-practitioner/',
                'registration_deadline' => Carbon::now()->addDays(14),
                'is_registration_open' => true,
                'quota' => 500,
                'tags' => ['aws', 'cloud', 'devops'],
                'logo' => 'sertifikasi/logos/aws-logo.png',
            ],
            [
                'title' => 'Belajar Dasar Pemrograman Web',
                'provider_name' => 'Dicoding Indonesia',
                'description' => 'Pelajari komponen dasar pembentuk website seperti HTML, CSS, dan teknik layouting agar website tampak rapi.',
                'content' => '<p>Kelas ini ditujukan bagi pemula yang ingin memulai karir sebagai Web Developer. Di akhir kelas, siswa akan bisa membuat halaman web sederhana yang responsif.</p>',
                'categories' => ['Web Development', 'Programming'],
                'type' => 'Kursus',
                'level' => 'Beginner',
                'mode' => 'Online',
                'location' => null,
                'duration' => '40 Jam',
                'is_self_paced' => true,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(1),
                'fee' => 0,
                'is_free' => true,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>PC/Laptop spek standar</li><li>Koneksi internet</li></ul>',
                'benefits' => '<ul><li>Sertifikat kompetensi</li><li>Code review dari expert</li></ul>',
                'syllabus' => '<ul><li>Pengenalan HTML</li><li>Pengenalan CSS</li><li>Layouting (Flexbox)</li><li>Responsive Design</li></ul>',
                'registration_url' => 'https://www.dicoding.com/academies/123',
                'registration_deadline' => Carbon::now()->addDays(7),
                'is_registration_open' => true,
                'quota' => 1000,
                'tags' => ['html', 'css', 'web-design', 'dicoding'],
                'logo' => 'sertifikasi/logos/dicoding-logo.png',
            ],
            [
                'title' => 'Cisco Certified Network Associate (CCNA)',
                'provider_name' => 'Cisco',
                'description' => 'Sertifikasi jaringan paling populer untuk membuktikan kemampuan Anda dalam menavigasi lanskap teknologi jaringan yang selalu berubah.',
                'content' => '<p>Ujian CCNA v1.0 (200-301) adalah ujian 120 menit yang terkait dengan sertifikasi CCNA. Ujian ini menguji pengetahuan dan keterampilan kandidat terkait fundamental jaringan, akses jaringan, konektivitas IP, layanan IP, fundamental keamanan, serta otomatisasi dan programabilitas.</p>',
                'categories' => ['Networking', 'Cybersecurity'],
                'type' => 'Sertifikasi',
                'level' => 'Intermediate',
                'mode' => 'Hybrid',
                'location' => 'Pearson VUE Test Centers / Online',
                'duration' => '120 Menit (Ujian)',
                'is_self_paced' => false,
                'start_date' => Carbon::now()->addMonths(1),
                'end_date' => Carbon::now()->addMonths(1),
                'fee' => 4500000,
                'is_free' => false,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>Pemahaman mendalam tentang jaringan IP</li><li>Satu tahun pengalaman kerja dengan solusi Cisco (disarankan)</li></ul>',
                'benefits' => '<ul><li>Validasi skill jaringan level associate</li><li>Peluang karir Network Engineer</li></ul>',
                'syllabus' => '<ul><li>Network Fundamentals</li><li>Network Access</li><li>IP Connectivity</li><li>Automation and Programmability</li></ul>',
                'registration_url' => 'https://www.cisco.com/c/en/us/training-events/training-certifications/certifications/associate/ccna.html',
                'registration_deadline' => Carbon::now()->addDays(20),
                'is_registration_open' => true,
                'quota' => 50,
                'tags' => ['cisco', 'networking', 'ccna', 'hardware'],
                'logo' => 'sertifikasi/logos/cisco-logo.png',
            ],
            [
                'title' => 'Oracle Certified Professional: Java SE 17 Developer',
                'provider_name' => 'Oracle',
                'description' => 'Buktikan keahlian Anda dalam bahasa pemrograman Java dan dapatkan pengakuan global sebagai Java Developer profesional.',
                'content' => '<p>Sertifikasi ini menunjukkan kemahiran dalam Java (Standard Edition) dan pemahaman mendalam tentang fitur-fitur modern Java 17.</p>',
                'categories' => ['Programming', 'Software Engineering'],
                'type' => 'Sertifikasi',
                'level' => 'Advanced',
                'mode' => 'Online',
                'location' => null,
                'duration' => '90 Menit (Ujian)',
                'is_self_paced' => true,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addYears(1),
                'fee' => 3700000,
                'is_free' => false,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>Pengalaman coding Java yang solid</li><li>Pemahaman OOP yang kuat</li></ul>',
                'benefits' => '<ul><li>Sertifikasi OCP yang prestisius</li><li>Kredibilitas tinggi di mata employer</li></ul>',
                'syllabus' => '<ul><li>Handling Date, Time, Text, Numeric and Boolean values</li><li>Controlling Program Flow</li><li>Java Object-Oriented Approach</li><li>Exception Handling</li></ul>',
                'registration_url' => 'https://education.oracle.com/java-se-17-developer/pexam_1Z0-829',
                'registration_deadline' => Carbon::now()->addDays(60),
                'is_registration_open' => true,
                'quota' => null,
                'tags' => ['java', 'oracle', 'backend', 'oop'],
                'logo' => 'sertifikasi/logos/oracle-logo.png',
            ],
            [
                'title' => 'Project Management Professional (PMP)®',
                'provider_name' => 'Project Management Institute (PMI)',
                'description' => 'Sertifikasi manajemen proyek terkemuka di dunia. PMP membuktikan keahlian kepemimpinan proyek dan cara kerja Anda.',
                'content' => '<p>PMP memvalidasi bahwa Anda memiliki keterampilan kepemimpinan proyek yang sangat dicari oleh pengusaha. PMP mencakup tiga pendekatan utama: Prediktif (Waterfall), Agile, dan Hibrida.</p>',
                'categories' => ['Management', 'Business'],
                'type' => 'Sertifikasi',
                'level' => 'Advanced',
                'mode' => 'Hybrid',
                'location' => 'Jakarta / Online',
                'duration' => '230 Menit (Ujian)',
                'is_self_paced' => false,
                'start_date' => Carbon::now()->addMonths(2),
                'end_date' => Carbon::now()->addMonths(2),
                'fee' => 8500000,
                'is_free' => false,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>Gelar Sarjana + 36 bulan pengalaman memimpin proyek</li><li>35 jam pendidikan manajemen proyek</li></ul>',
                'benefits' => '<ul><li>Gaji rata-rata lebih tinggi</li><li>Pengakuan global</li></ul>',
                'syllabus' => '<ul><li>People (42%)</li><li>Process (50%)</li><li>Business Environment (8%)</li></ul>',
                'registration_url' => 'https://www.pmi.org/certifications/project-management-pmp',
                'registration_deadline' => Carbon::now()->addDays(45),
                'is_registration_open' => true,
                'quota' => 30,
                'tags' => ['management', 'pmp', 'agile', 'scrum'],
                'logo' => 'sertifikasi/logos/pmi-logo.png',
            ],
            [
                'title' => 'The Complete 2024 Web Development Bootcamp',
                'provider_name' => 'Udemy (Dr. Angela Yu)',
                'description' => 'Menjadi Full-Stack Web Developer hanya dengan satu kursus. HTML, CSS, Javascript, Node, React, MongoDB, Web3 dan DApps.',
                'content' => '<p>Salah satu kursus web development terlengkap dan terlaris di Udemy. Cocok untuk pemula mutlak hingga advanced.</p>',
                'categories' => ['Web Development', 'Fullstack'],
                'type' => 'Kursus',
                'level' => 'All Levels',
                'mode' => 'Online',
                'location' => null,
                'duration' => '65 Jam Video',
                'is_self_paced' => true,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'fee' => 129000,
                'is_free' => false,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>Komputer dengan akses internet</li><li>Tidak perlu pengalaman coding sebelumnya</li></ul>',
                'benefits' => '<ul><li>Akses seumur hidup</li><li>Portofolio project nyata</li></ul>',
                'syllabus' => '<ul><li>Front-End Web Development</li><li>Back-End Web Development</li><li>React.js</li><li>Databases (SQL & NoSQL)</li></ul>',
                'registration_url' => 'https://www.udemy.com/course/the-complete-web-development-bootcamp/',
                'registration_deadline' => Carbon::now()->addDays(5),
                'is_registration_open' => true,
                'quota' => null,
                'tags' => ['fullstack', 'react', 'node', 'bootcamp'],
                'logo' => 'sertifikasi/logos/udemy-logo.png',
            ],
            [
                'title' => 'Fundamentals of Digital Marketing',
                'provider_name' => 'Google Digital Garage',
                'description' => 'Kuasai dasar-dasar pemasaran digital dengan kursus gratis Interactive Advertising Bureau Europe dan The Open University.',
                'content' => '<p>Ada 26 modul untuk dipelajari, semuanya dibuat oleh pelatih Google, dikemas penuh dengan latihan praktis dan contoh dunia nyata untuk membantu Anda mengubah pengetahuan menjadi tindakan.</p>',
                'categories' => ['Digital Marketing', 'Business'],
                'type' => 'Kursus',
                'level' => 'Beginner',
                'mode' => 'Online',
                'location' => null,
                'duration' => '40 Jam',
                'is_self_paced' => true,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(2),
                'fee' => 0,
                'is_free' => true,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>Minat di bidang marketing</li></ul>',
                'benefits' => '<ul><li>Sertifikat gratis dari Google</li><li>Skill fundamental bisnis online</li></ul>',
                'syllabus' => '<ul><li>Membangun kehadiran web</li><li>Merencanakan strategi bisnis online</li><li>Search Engine Optimization (SEO)</li></ul>',
                'registration_url' => 'https://skillshop.exceedlms.com/student/collection/64838-digital-marketing',
                'registration_deadline' => Carbon::now()->addDays(90),
                'is_registration_open' => true,
                'quota' => null,
                'tags' => ['marketing', 'seo', 'google', 'business'],
                'logo' => 'sertifikasi/logos/google-garage-logo.png',
            ],
            [
                'title' => 'TOEFL ITP Preparation & Test',
                'provider_name' => 'LBI Universitas Indonesia',
                'description' => 'Program persiapan intensif untuk menghadapi ujian TOEFL ITP guna keperluan akademik maupun profesional.',
                'content' => '<p>Program ini dirancang untuk meningkatkan skor TOEFL peserta melalui latihan soal Listening, Structure, dan Reading Comprehension secara intensif.</p>',
                'categories' => ['Language', 'Academic'],
                'type' => 'Workshop',
                'level' => 'Intermediate',
                'mode' => 'Online',
                'location' => 'Zoom Meeting',
                'duration' => '2 Minggu (10 Sesi)',
                'is_self_paced' => false,
                'start_date' => Carbon::now()->addWeeks(2),
                'end_date' => Carbon::now()->addWeeks(4),
                'fee' => 1500000,
                'is_free' => false,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>Pre-test score min. 400</li><li>Komitmen hadir di setiap sesi</li></ul>',
                'benefits' => '<ul><li>Simulasi ujian TOEFL</li><li>Tips & Trik mengerjakan soal</li><li>Sertifikat kepesertaan</li></ul>',
                'syllabus' => '<ul><li>Listening Comprehension Strategies</li><li>Structure and Written Expression</li><li>Reading Comprehension Tactics</li></ul>',
                'registration_url' => 'https://lbifib.ui.ac.id/',
                'registration_deadline' => Carbon::now()->addDays(3),
                'is_registration_open' => true,
                'quota' => 20,
                'tags' => ['toefl', 'english', 'language', 'academic'],
                'logo' => 'sertifikasi/logos/lbifibui-logo.png',
            ],
            [
                'title' => 'CompTIA Security+',
                'provider_name' => 'CompTIA',
                'description' => 'CompTIA Security+ adalah sertifikasi global yang memvalidasi keterampilan dasar yang diperlukan untuk melakukan fungsi keamanan inti.',
                'content' => '<p>Security+ menetapkan standar inti untuk karir cybersecurity dan menggabungkan praktik terbaik dalam pemecahan masalah langsung untuk memastikan para profesional memiliki keterampilan pemecahan masalah keamanan praktis.</p>',
                'categories' => ['Cybersecurity', 'IT Infrastructure'],
                'type' => 'Sertifikasi',
                'level' => 'Beginner',
                'mode' => 'Offline',
                'location' => 'Pearson VUE Centers (Jakarta/Bandung)',
                'duration' => '90 Menit',
                'is_self_paced' => true,
                'start_date' => Carbon::now(),
                'end_date' => Carbon::now()->addMonths(6),
                'fee' => 5800000,
                'is_free' => false,
                'fee_currency' => 'IDR',
                'requirements' => '<ul><li>CompTIA Network+ dan dua tahun pengalaman di administrasi IT dengan fokus keamanan</li></ul>',
                'benefits' => '<ul><li>Pintu masuk karir Cyber Security</li><li>Diakui Departemen Pertahanan AS</li></ul>',
                'syllabus' => '<ul><li>Attacks, Threats and Vulnerabilities</li><li>Architecture and Design</li><li>Implementation</li><li>Operations and Incident Response</li></ul>',
                'registration_url' => 'https://www.comptia.org/certifications/security',
                'registration_deadline' => Carbon::now()->addDays(30),
                'is_registration_open' => true,
                'quota' => null,
                'tags' => ['security', 'cybersecurity', 'comptia', 'network'],
                'logo' => 'sertifikasi/logos/comptia-logo.png',
            ],
        ];

        foreach ($sertifikasis as $data) {
            $data['slug'] = Str::slug($data['title']) . '-' . Str::random(5);
            $data['status'] = 'Published';
            $data['published_at'] = Carbon::now();
            $data['view_count'] = rand(50, 5000);
            $data['enrolled_count'] = rand(0, 100);
            Sertifikasi::create($data);
        }
    }
}
